name: psione_egg
description: Primeira fase do ÏˆONE - Ovo cognitivo
publish_to: none
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
